// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwtdbchibdhnhpstrrod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3dGRiY2hpYmRobmhwc3Rycm9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjMxODIsImV4cCI6MjA2NTczOTE4Mn0.sUktFxB2et9yid7MoWudHks8u4cSLevozHmBYPD64cg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);